<a href="https://colab.research.google.com/github/Sweta-Das/TensorFlow-Python-Projects/blob/Fundamentals/1-TensorFlow_Basics/1_TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.15.0


### Creating Tensors
Defining tensors with their datatypes.

In [ ]:
str = tf.Variable("This is a string!", tf.string)
str

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string!'>

In [ ]:
num = tf.Variable(121, tf.int16)
num

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=121>

In [ ]:
flo = tf.Variable(1.23, tf.float32)
flo

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.23>

### Rank/Degree of Tensors
Rank or degree of tensors mean the number of dimensions involved in the tensor.

Rank-0 or Scalar Tensor

In [ ]:
num

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=121>

Rank-1 Tensor

In [ ]:
r1 = tf.Variable(["This is rank-1"], tf.string)
print(r1)
r1_ = tf.Variable(["This", "is", "rank-1"], tf.string)
print(r1_)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'This is rank-1'], dtype=object)>
<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'This', b'is', b'rank-1'], dtype=object)>


Rank-2 Tensor

In [ ]:
r2 = tf.Variable([["This", "is "], ["rank-2", "tensor"]], tf.string)
r2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'This', b'is '],
       [b'rank-2', b'tensor']], dtype=object)>

Determining rank of a tensor.

In [ ]:
tf.rank(r1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(r1_)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(r2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.rank(str)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### Shape of Tensors
It is the amount of elements that exist in each dimension.

In [ ]:
num.shape

TensorShape([])

In [ ]:
r1.shape

TensorShape([1])

In [ ]:
r1_.shape

TensorShape([3])

In [ ]:
r2.shape

TensorShape([2, 2])

It means that it has 2 lists where each list has 2 elements in it.

In [ ]:
# Changing the shape of a tensor

tnsr1 = tf.ones([1, 2, 3])
tnsr1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
# Reshaping tnsr1 to 2 lists, 3 inside of those and each has 1 element
tnsr2 = tf.reshape(tnsr1, [2, 3, 1])
tnsr2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
# Reshaping tnsr2 to 3 lists
tnsr3 = tf.reshape(tnsr2, [3, -1])
tnsr3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

`-1` tells the tensor to calculate the size of dimension suitably in that place based on the number of elements present. It'll give a required number and generate 3 lists respectively.

In [ ]:
tnsr3.shape

TensorShape([3, 2])

Creating a tensor with zeros only with the dimension of 5x5.

In [2]:
tnsr = tf.zeros([5, 5, 5, 5])
tnsr

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [3]:
# Reshaping the above tensor by flattening it
tnsr_flt = tf.reshape(tnsr, [625])
tnsr_flt

<tf.Tensor: shape=(625,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [5]:
# Reshaping again to 125 sub-lists
tnsr_flt2 = tf.reshape(tnsr, [125, -1])
tnsr_flt2

<tf.Tensor: shape=(125, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0.

###Evaluating Tensors
Since tensors represent a partially complete computation, we may need to run *session* to evaluate the tensor.

In [ ]:
with tf.Session() as sess:
  print(tnsr3.eval())