In [1]:
import tensorflow as tf

In [2]:
# Defining tensors
tnsr_a = tf.constant([1, 2, 3])
tnsr_a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

Operations on Tensors

In [3]:
# Performing operations on tensors
tnsr_b = tf.constant([4, 5, 6])
tnsr_sum = tf.add(tnsr_a, tnsr_b)
tnsr_sum

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [4]:
tnsr_sub = tf.subtract(tnsr_b, tnsr_a)
tnsr_sub

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 3, 3])>

In [5]:
tnsr_prod = tf.multiply(tnsr_sum, tnsr_sub)
tnsr_prod

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 21, 27])>

Tensor Graphs

In [6]:
# Defining a graph
graph = tf.Graph()

# Adding operations to the graph
with graph.as_default():
  # Tensors
  tnsr_c = tf.constant([8, 9, 5])
  tnsr_d = tf.constant([4, 7, 3])

  # Operations
  tnsr_sum = tf.add(tnsr_c, tnsr_d)
  tnsr_prod = tf.multiply(tnsr_sum, tnsr_d)

# Executing operaions within a session
with tf.compat.v1.Session(graph=graph) as sess:
  sum_res, prod_res = sess.run([tnsr_sum, tnsr_prod])
  print("Sum: ", sum_res)
  print("Product: ", prod_res)


Sum:  [12 16  8]
Product:  [ 48 112  24]


Advantages of using TensorFlow graph: <br>
- **Optimization**: TensorFlow can optimize the computations defined in a graph through constant folding, common sub-expression elimination, and kernel fusion, leading to improved performance, especially in GPUs.
- **Portability**: A graph and its associated variables can be saved to a file, making it easy to deploy it to different environments, or even using it in other programming languages through TF's language bindings.
- **Parallelism**: TensorFlow can analyze the dependencies between operations in the graph & execute them in parallel when possible, leading to better utilization of computational resources.
- **Distributed Computing**: TensorFlow supports distributed computing across multiple devices & machines. On defining computation in a graph, we can run it on a cluster of machines.
- **Debugging & Viz.**: Graph can be vizualized & debugged through tools like TensorBoard. This can help to understand the structure of computation, identify bottlenecks, and optimize the model.

In [7]:
# Writing the graph to a log directory and launching TensorBoard
with tf.summary.create_file_writer('./logs').as_default():
    tf.summary.trace_on(graph=True, profiler=False)
    tf.summary.trace_export(name="graph_trace", step=0)

In [8]:
!tensorboard --logdir=./logs

^C


### Data Types and Constants

In [9]:
# Float (32-bit, 64-bit)
tnsr_flt = tf.constant([1.0, 5.0, 4.0], dtype=tf.float32)
tnsr_dbl = tf.constant([1.0, 5.0, 3.0], dtype=tf.float64)
print(tnsr_flt, tnsr_dbl)

tf.Tensor([1. 5. 4.], shape=(3,), dtype=float32) tf.Tensor([1. 5. 3.], shape=(3,), dtype=float64)


In [10]:
# Integer (32-bit, 64-bit)
tnsr_int = tf.constant([4, 6, 7], dtype=tf.int32)
tnsr_lng = tf.constant([3, 4, 5], dtype=tf.int64)
print(tnsr_int, tnsr_lng)

tf.Tensor([4 6 7], shape=(3,), dtype=int32) tf.Tensor([3 4 5], shape=(3,), dtype=int64)


In [11]:
# Boolean
tnsr_bool = tf.constant([True, False, True, True],dtype=tf.bool)
tnsr_bool

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [12]:
# String
tnsr_str = tf.constant(["Hey!", "Stay Strong."], dtype=tf.string)
tnsr_str

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hey!', b'Stay Strong.'], dtype=object)>

In [13]:
# Complex
tnsr_cmplx = tf.constant([1+2j, 3+6j], dtype=tf.complex64)
tnsr_cmplx

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.+2.j, 3.+6.j], dtype=complex64)>

In [14]:
# 8-bit Unsigned Integer
tnsr_uint8 = tf.constant([0, 145, 677], dtype=tf.uint8)
tnsr_uint8

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([  0, 145, 165], dtype=uint8)>

### Variables and Placeholders

Variables

In [15]:
var_a = tf.Variable(2, name='var_a')
var_b = tf.Variable(7, name='var_b')
var_b

<tf.Variable 'var_b:0' shape=() dtype=int32, numpy=7>

In [16]:
# Ops with Variables
var_sum = tf.add(var_a, var_b)
var_sum

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [17]:
var_prod = tf.multiply(var_a, var_sum)
var_prod

<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [20]:
# Graph with Variables
graph_var = tf.Graph()

with graph_var.as_default():
  var_a = tf.Variable(2, name='var_a')
  var_b = tf.Variable(7, name='var_b')

  # Operation to initialize variables
  init = tf.compat.v1.global_variables_initializer()

  var_prod = tf.multiply(var_a, var_b)

with tf.compat.v1.Session(graph=graph_var) as sess:
  # Initializing variables
  sess.run(init)

  res = sess.run(var_prod)
  print("Variable Product: ", res)

Variable Product:  14


Placeholders

In [23]:
# Defining a graph
graph_ph = tf.Graph()

# Operation
with graph_ph.as_default():
    # Placeholders
    x = tf.compat.v1.placeholder(tf.float32)
    y = tf.compat.v1.placeholder(tf.float32)
    
    z = tf.add(x, y)

# Graph
with tf.compat.v1.Session(graph=graph_ph) as sess:
    # Executing the graph with feed_dict to provide values for placeholders
    result = sess.run(z, feed_dict={x: 2.0, y: 3.0})
    print("Result:", result)

Result: 5.0


The key difference between variables and placeholders is that variables hold values that can be modified and updated during training, while placeholders are used to feed actual data into the TensorFlow graph during execution.

### Session and Executions

Basic Example

In [25]:
# Define a computational graph
graph = tf.Graph()

with graph.as_default():
    a = tf.constant(2)
    b = tf.constant(3)
    c = tf.add(a, b)

# Create a session
with tf.compat.v1.Session(graph=graph) as sess:
    # Execute the graph
    result = sess.run(c)
    print("Result:", result)

Result: 5


Placeholder Example

In [26]:
graph_ph

In [27]:
with graph_ph.as_default():
    x = tf.compat.v1.placeholder(tf.float32)
    y = tf.compat.v1.placeholder(tf.float32)
    z = tf.multiply(x, y)

with tf.compat.v1.Session(graph=graph_ph) as sess:
    # Execute the graph by providing values for placeholders
    result = sess.run(z, feed_dict={x: 2.0, y: 3.0})
    print("Result:", result)

Result: 6.0


Variable Example

In [28]:
graph_var

In [29]:
with graph_var.as_default():
    var = tf.Variable(2.0, dtype=tf.float32)
    multiply_op = var * 3

    # Initialize variables operation
    init_vars = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session(graph=graph_var) as sess:
    sess.run(init_vars)
    result = sess.run(multiply_op)
    print("Result:", result) 

Result: 6.0
